-- Lift: seed built-in exercises (~50)

INSERT INTO exercises (user_id, name, exercise_type, category, primary_muscles, equipment) VALUES
(NULL, 'Barbell Bench Press', 'strength', 'push', ARRAY['chest', 'triceps'], 'barbell'),
(NULL, 'Incline Barbell Bench Press', 'strength', 'push', ARRAY['chest', 'shoulders'], 'barbell'),
(NULL, 'Dumbbell Bench Press', 'strength', 'push', ARRAY['chest', 'triceps'], 'dumbbell'),
(NULL, 'Incline Dumbbell Press', 'strength', 'push', ARRAY['chest', 'shoulders'], 'dumbbell'),
(NULL, 'Overhead Press', 'strength', 'push', ARRAY['shoulders', 'triceps'], 'barbell'),
(NULL, 'Dumbbell Shoulder Press', 'strength', 'push', ARRAY['shoulders', 'triceps'], 'dumbbell'),
(NULL, 'Push-Up', 'bodyweight', 'push', ARRAY['chest', 'triceps'], 'bodyweight'),
(NULL, 'Dips', 'bodyweight', 'push', ARRAY['chest', 'triceps'], 'bodyweight'),
(NULL, 'Tricep Pushdown', 'strength', 'push', ARRAY['triceps'], 'cable'),
(NULL, 'Skull Crushers', 'strength', 'push', ARRAY['triceps'], 'barbell'),
(NULL, 'Lateral Raise', 'strength', 'push', ARRAY['shoulders'], 'dumbbell'),
(NULL, 'Cable Fly', 'strength', 'push', ARRAY['chest'], 'cable'),
(NULL, 'Deadlift', 'strength', 'pull', ARRAY['back', 'hamstrings', 'glutes'], 'barbell'),
(NULL, 'Romanian Deadlift', 'strength', 'pull', ARRAY['hamstrings', 'glutes'], 'barbell'),
(NULL, 'Barbell Row', 'strength', 'pull', ARRAY['back', 'biceps'], 'barbell'),
(NULL, 'Dumbbell Row', 'strength', 'pull', ARRAY['back', 'biceps'], 'dumbbell'),
(NULL, 'Pull-Up', 'bodyweight', 'pull', ARRAY['back', 'biceps'], 'bodyweight'),
(NULL, 'Chin-Up', 'bodyweight', 'pull', ARRAY['back', 'biceps'], 'bodyweight'),
(NULL, 'Lat Pulldown', 'strength', 'pull', ARRAY['back', 'biceps'], 'cable'),
(NULL, 'Seated Cable Row', 'strength', 'pull', ARRAY['back', 'biceps'], 'cable'),
(NULL, 'Face Pull', 'strength', 'pull', ARRAY['rear delts', 'back'], 'cable'),
(NULL, 'Barbell Curl', 'strength', 'pull', ARRAY['biceps'], 'barbell'),
(NULL, 'Dumbbell Curl', 'strength', 'pull', ARRAY['biceps'], 'dumbbell'),
(NULL, 'Hammer Curl', 'strength', 'pull', ARRAY['biceps', 'forearms'], 'dumbbell'),
(NULL, 'Back Squat', 'strength', 'legs', ARRAY['quads', 'glutes'], 'barbell'),
(NULL, 'Front Squat', 'strength', 'legs', ARRAY['quads', 'core'], 'barbell'),
(NULL, 'Leg Press', 'strength', 'legs', ARRAY['quads', 'glutes'], 'machine'),
(NULL, 'Leg Extension', 'strength', 'legs', ARRAY['quads'], 'machine'),
(NULL, 'Leg Curl', 'strength', 'legs', ARRAY['hamstrings'], 'machine'),
(NULL, 'Bulgarian Split Squat', 'strength', 'legs', ARRAY['quads', 'glutes'], 'dumbbell'),
(NULL, 'Walking Lunge', 'strength', 'legs', ARRAY['quads', 'glutes'], 'dumbbell'),
(NULL, 'Goblet Squat', 'strength', 'legs', ARRAY['quads', 'glutes'], 'dumbbell'),
(NULL, 'Hip Thrust', 'strength', 'legs', ARRAY['glutes', 'hamstrings'], 'barbell'),
(NULL, 'Calf Raise', 'strength', 'legs', ARRAY['calves'], 'machine'),
(NULL, 'Plank', 'bodyweight', 'core', ARRAY['core'], 'bodyweight'),
(NULL, 'Hanging Leg Raise', 'bodyweight', 'core', ARRAY['core'], 'bodyweight'),
(NULL, 'Cable Crunch', 'strength', 'core', ARRAY['core'], 'cable'),
(NULL, 'Ab Wheel Rollout', 'bodyweight', 'core', ARRAY['core'], 'bodyweight'),
(NULL, 'Russian Twist', 'bodyweight', 'core', ARRAY['core'], 'bodyweight'),
(NULL, 'Treadmill Run', 'cardio', 'cardio', ARRAY['cardio'], 'treadmill'),
(NULL, 'Outdoor Run', 'cardio', 'cardio', ARRAY['cardio'], 'none'),
(NULL, 'Stationary Bike', 'cardio', 'cardio', ARRAY['cardio'], 'bike'),
(NULL, 'Rowing Machine', 'cardio', 'cardio', ARRAY['cardio'], 'rower'),
(NULL, 'Elliptical', 'cardio', 'cardio', ARRAY['cardio'], 'elliptical'),
(NULL, 'Stair Climber', 'cardio', 'cardio', ARRAY['cardio'], 'machine'),
(NULL, 'Jump Rope', 'cardio', 'cardio', ARRAY['cardio'], 'rope'),
(NULL, 'Kettlebell Swing', 'strength', 'legs', ARRAY['glutes', 'hamstrings'], 'kettlebell'),
(NULL, 'Farmer''s Walk', 'strength', 'core', ARRAY['forearms', 'core'], 'dumbbell'),
(NULL, 'Shrugs', 'strength', 'pull', ARRAY['traps'], 'barbell'),
(NULL, 'Preacher Curl', 'strength', 'pull', ARRAY['biceps'], 'barbell');
