-- Lift: expand built-in exercise library (82 additional exercises)
-- Categories: arms, chest, shoulders, back, core, legs, cardio

INSERT INTO exercises (user_id, name, exercise_type, category, primary_muscles, equipment) VALUES
-- Chest
(NULL, 'Decline Barbell Bench Press', 'strength', 'chest', ARRAY['chest', 'triceps'], 'barbell'),
(NULL, 'Decline Dumbbell Press', 'strength', 'chest', ARRAY['chest', 'triceps'], 'dumbbell'),
(NULL, 'Machine Chest Press', 'strength', 'chest', ARRAY['chest', 'triceps'], 'machine'),
(NULL, 'Dumbbell Fly', 'strength', 'chest', ARRAY['chest'], 'dumbbell'),
(NULL, 'Incline Dumbbell Fly', 'strength', 'chest', ARRAY['chest'], 'dumbbell'),
(NULL, 'Incline Cable Fly', 'strength', 'chest', ARRAY['chest'], 'cable'),
(NULL, 'Pec Deck', 'strength', 'chest', ARRAY['chest'], 'machine'),
(NULL, 'Close-Grip Bench Press', 'strength', 'chest', ARRAY['chest', 'triceps'], 'barbell'),
(NULL, 'Floor Press', 'strength', 'chest', ARRAY['chest', 'triceps'], 'barbell'),
(NULL, 'Landmine Press', 'strength', 'chest', ARRAY['chest', 'shoulders'], 'barbell'),
-- Shoulders
(NULL, 'Rear Delt Fly', 'strength', 'shoulders', ARRAY['rear delts'], 'dumbbell'),
(NULL, 'Front Raise', 'strength', 'shoulders', ARRAY['shoulders'], 'dumbbell'),
(NULL, 'Arnold Press', 'strength', 'shoulders', ARRAY['shoulders', 'triceps'], 'dumbbell'),
(NULL, 'Cable Lateral Raise', 'strength', 'shoulders', ARRAY['shoulders'], 'cable'),
(NULL, 'Machine Shoulder Press', 'strength', 'shoulders', ARRAY['shoulders', 'triceps'], 'machine'),
(NULL, 'Push Press', 'strength', 'shoulders', ARRAY['shoulders', 'triceps'], 'barbell'),
(NULL, 'Reverse Pec Deck', 'strength', 'shoulders', ARRAY['rear delts'], 'machine'),
(NULL, 'Cable Face Pull', 'strength', 'shoulders', ARRAY['rear delts', 'back'], 'cable'),
-- Arms
(NULL, 'Overhead Tricep Extension', 'strength', 'arms', ARRAY['triceps'], 'dumbbell'),
(NULL, 'Cable Overhead Tricep Extension', 'strength', 'arms', ARRAY['triceps'], 'cable'),
(NULL, 'Tricep Kickback', 'strength', 'arms', ARRAY['triceps'], 'dumbbell'),
(NULL, 'Close-Grip Push-Up', 'bodyweight', 'arms', ARRAY['triceps', 'chest'], 'bodyweight'),
(NULL, 'Diamond Push-Up', 'bodyweight', 'arms', ARRAY['triceps', 'chest'], 'bodyweight'),
(NULL, 'EZ Bar Curl', 'strength', 'arms', ARRAY['biceps'], 'barbell'),
(NULL, 'Concentration Curl', 'strength', 'arms', ARRAY['biceps'], 'dumbbell'),
(NULL, 'Incline Dumbbell Curl', 'strength', 'arms', ARRAY['biceps'], 'dumbbell'),
(NULL, 'Spider Curl', 'strength', 'arms', ARRAY['biceps'], 'dumbbell'),
(NULL, 'Reverse Curl', 'strength', 'arms', ARRAY['forearms', 'biceps'], 'barbell'),
(NULL, 'Wrist Curl', 'strength', 'arms', ARRAY['forearms'], 'dumbbell'),
(NULL, 'Reverse Wrist Curl', 'strength', 'arms', ARRAY['forearms'], 'dumbbell'),
(NULL, 'Cable Curl', 'strength', 'arms', ARRAY['biceps'], 'cable'),
-- Back
(NULL, 'Sumo Deadlift', 'strength', 'back', ARRAY['back', 'glutes', 'hamstrings'], 'barbell'),
(NULL, 'Trap Bar Deadlift', 'strength', 'back', ARRAY['back', 'glutes', 'hamstrings'], 'barbell'),
(NULL, 'Rack Pull', 'strength', 'back', ARRAY['back', 'glutes'], 'barbell'),
(NULL, 'T-Bar Row', 'strength', 'back', ARRAY['back', 'biceps'], 'barbell'),
(NULL, 'Pendlay Row', 'strength', 'back', ARRAY['back', 'biceps'], 'barbell'),
(NULL, 'Chest-Supported Row', 'strength', 'back', ARRAY['back', 'biceps'], 'machine'),
(NULL, 'Single-Arm Cable Row', 'strength', 'back', ARRAY['back', 'biceps'], 'cable'),
(NULL, 'Inverted Row', 'bodyweight', 'back', ARRAY['back', 'biceps'], 'bodyweight'),
(NULL, 'Straight-Arm Pulldown', 'strength', 'back', ARRAY['back'], 'cable'),
(NULL, 'Cable Pullover', 'strength', 'back', ARRAY['back', 'chest'], 'cable'),
(NULL, 'Wide-Grip Pull-Up', 'bodyweight', 'back', ARRAY['back', 'biceps'], 'bodyweight'),
(NULL, 'Neutral-Grip Pull-Up', 'bodyweight', 'back', ARRAY['back', 'biceps'], 'bodyweight'),
(NULL, 'Back Extension', 'bodyweight', 'back', ARRAY['back', 'glutes'], 'bodyweight'),
(NULL, 'Good Morning', 'strength', 'back', ARRAY['back', 'hamstrings'], 'barbell'),
-- Core
(NULL, 'Dead Bug', 'bodyweight', 'core', ARRAY['core'], 'bodyweight'),
(NULL, 'Side Plank', 'bodyweight', 'core', ARRAY['core'], 'bodyweight'),
(NULL, 'Pallof Press', 'strength', 'core', ARRAY['core'], 'cable'),
(NULL, 'Bicycle Crunch', 'bodyweight', 'core', ARRAY['core'], 'bodyweight'),
(NULL, 'Toes to Bar', 'bodyweight', 'core', ARRAY['core'], 'bodyweight'),
(NULL, 'V-Up', 'bodyweight', 'core', ARRAY['core'], 'bodyweight'),
(NULL, 'Sit-Up', 'bodyweight', 'core', ARRAY['core'], 'bodyweight'),
(NULL, 'Decline Sit-Up', 'bodyweight', 'core', ARRAY['core'], 'bodyweight'),
(NULL, 'Wood Chop', 'strength', 'core', ARRAY['core'], 'cable'),
(NULL, 'Superman', 'bodyweight', 'core', ARRAY['back', 'core'], 'bodyweight'),
(NULL, 'Hollow Body Hold', 'bodyweight', 'core', ARRAY['core'], 'bodyweight'),
(NULL, 'Mountain Climber', 'bodyweight', 'core', ARRAY['core', 'cardio'], 'bodyweight'),
-- Legs
(NULL, 'Reverse Lunge', 'strength', 'legs', ARRAY['quads', 'glutes'], 'dumbbell'),
(NULL, 'Step-Up', 'strength', 'legs', ARRAY['quads', 'glutes'], 'dumbbell'),
(NULL, 'Hack Squat', 'strength', 'legs', ARRAY['quads', 'glutes'], 'machine'),
(NULL, 'Smith Machine Squat', 'strength', 'legs', ARRAY['quads', 'glutes'], 'machine'),
(NULL, 'Box Squat', 'strength', 'legs', ARRAY['quads', 'glutes'], 'barbell'),
(NULL, 'Sumo Squat', 'strength', 'legs', ARRAY['quads', 'glutes'], 'dumbbell'),
(NULL, 'Glute Bridge', 'strength', 'legs', ARRAY['glutes', 'hamstrings'], 'barbell'),
(NULL, 'Single-Leg Romanian Deadlift', 'strength', 'legs', ARRAY['hamstrings', 'glutes'], 'dumbbell'),
(NULL, 'Cable Pull-Through', 'strength', 'legs', ARRAY['glutes', 'hamstrings'], 'cable'),
(NULL, 'Standing Calf Raise', 'strength', 'legs', ARRAY['calves'], 'machine'),
(NULL, 'Seated Calf Raise', 'strength', 'legs', ARRAY['calves'], 'machine'),
(NULL, 'Hip Abduction', 'strength', 'legs', ARRAY['glutes'], 'machine'),
(NULL, 'Hip Adduction', 'strength', 'legs', ARRAY['quads'], 'machine'),
(NULL, 'Pistol Squat', 'bodyweight', 'legs', ARRAY['quads', 'glutes'], 'bodyweight'),
(NULL, 'Box Jump', 'bodyweight', 'legs', ARRAY['quads', 'glutes'], 'box'),
(NULL, 'Thruster', 'strength', 'legs', ARRAY['quads', 'shoulders'], 'barbell'),
-- Cardio & conditioning
(NULL, 'Burpee', 'bodyweight', 'core', ARRAY['core', 'cardio'], 'bodyweight'),
(NULL, 'Indoor Cycling', 'cardio', 'cardio', ARRAY['cardio'], 'bike'),
(NULL, 'Outdoor Cycling', 'cardio', 'cardio', ARRAY['cardio'], 'bike'),
(NULL, 'Swimming', 'cardio', 'cardio', ARRAY['cardio'], 'none'),
(NULL, 'Hiking', 'cardio', 'cardio', ARRAY['cardio'], 'none'),
(NULL, 'Walking', 'cardio', 'cardio', ARRAY['cardio'], 'none'),
(NULL, 'Assault Bike', 'cardio', 'cardio', ARRAY['cardio'], 'bike'),
(NULL, 'Battle Ropes', 'cardio', 'cardio', ARRAY['cardio'], 'rope'),
(NULL, 'Stair Sprints', 'cardio', 'cardio', ARRAY['cardio'], 'machine');
